In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

In [2]:
x = tf.constant([[10.]]) #Input setting (input -> matrix)
#불변함수 지정할때는 constant, 변수 쓸 때는 variable
print(type(x)) #텐서플로우 내 타입. 파이썬의 구조랑 별개라고 보기

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [3]:
dense = Dense(units=1, activation='linear') #뉴런 몇 개 구성할 것인지 #imp. an affine function #항등함수 리니어 넣어보기로 한다.
#dense.get_weights() 여기서 불러오면 error → 왜냐하면 텐서 1.0 첫 사상은 lazy running이기에 선언 시 아직 x와 b가 초기화가 안 된 상태.
y_tf = dense(x) #forward propagation + params initialization z = xw+b #랜덤하게 초기화 됨.

W, b = dense.get_weights() # 이 메소드로 W와 b값 가져올 수 있음.
print(W, b, y_tf.numpy() ) # 10넣었을때 weight과 bias, 결과값 확인 #텐서타입에서 넘파이 타입으로 바꿔서 출력하는 것
print(type(W),type(b))

[[-0.6883842]] [0.] [[-6.8838415]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [4]:
y_man = tf.linalg.matmul(x,W) +b # 매뉴얼로 affine펑션 구현, matmul은 행렬곱인 matrix multiply

print('=======Input / Weight / Bias=======')
print('x: {}\n{}\n'.format(x.shape, x.numpy()))
print('W: {}\n{}\n'.format(W.shape, W))
print('b: {}\n{}\n'.format(b.shape, b))

print('=======output=======')
print('y(Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('y(Manual): {}\n{}\n'.format(y_man.shape, y_man.numpy()))

=======Input / Weight / Bias=======
x: (1, 1)
[[10.]]

W: (1, 1)
[[-0.6883842]]

b: (1,)
[0.]

=======output=======
y(Tensorflow): (1, 1)
[[-6.8838415]]

y(Manual): (1, 1)
[[-6.8838415]]



### Params Initialization

In [7]:
from tensorflow.keras.initializers import Constant

# weight / bias setting
W, b = (tf.constant(10.), tf.constant(20.))
w_init, b_init = Constant(10.), Constant(20.)

# 랜덤하게 초기화되는 부분을 고정시켜봄
dense = Dense(units = 1, activation = 'linear',
              kernel_initializer = w_init,
              bias_initializer=b_init)

y_tf = dense(x)
W, b = dense.get_weights()

print('W: {}\n{}\n'.format(W.shape, W))
print('b: {}\n{}\n'.format(b.shape, b))

W: (1, 1)
[[10.]]

b: (1,)
[20.]



In [6]:
print(y_tf.numpy())

[[120.]]


### Affine Functions w/ n Feature

In [8]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

tf.random.set_seed(10)
#random seed 같은 기능으로 timestamp처럼 기준시 있는데 default는 now니까 안 쓰면 랜덤하게 계속 바뀜
x = tf.random.uniform(shape=(1,10), minval=0, maxval=10)
dense = Dense(units=1) # act_f는 현재 없으므로 linear 통과한 것과 비슷하게 나올 것임.

In [9]:
x.numpy()

array([[6.4415097 , 8.082472  , 8.976547  , 6.3689017 , 6.270969  ,
        9.936013  , 0.23594856, 0.36683917, 5.8605776 , 5.7403145 ]],
      dtype=float32)

In [10]:
y_tf = dense(x)
W, b = dense.get_weights()
y_man = tf.linalg.matmul(x,W) + b

In [11]:
print('=======Input / Weight / Bias=======')
print('x: {}\n{}\n'.format(x.shape, x.numpy())) #row vector
print('W: {}\n{}\n'.format(W.shape, W)) #column vector
print('b: {}\n{}\n'.format(b.shape, b))

print('=======output=======')
print('y(Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('y(Manual): {}\n{}\n'.format(y_man.shape, y_man.numpy()))

=======Input / Weight / Bias=======
x: (1, 10)
[[6.4415097  8.082472   8.976547   6.3689017  6.270969   9.936013
  0.23594856 0.36683917 5.8605776  5.7403145 ]]

W: (10, 1)
[[ 0.08091772]
 [-0.10844558]
 [-0.5296768 ]
 [ 0.30087596]
 [-0.18808389]
 [ 0.29202002]
 [-0.39361012]
 [ 0.09546101]
 [-0.4453573 ]
 [ 0.6689041 ]]

b: (1,)
[0.]

=======output=======
y(Tensorflow): (1, 1)
[[-0.29983306]]

y(Manual): (1, 1)
[[-0.29983306]]



### Activation Functions

In [20]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

In [18]:
tf.random.set_seed(10)
x = tf.random.normal(shape=(1,5)) # 중복 안되게 난수 가져오는 함수
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation(tensorflow)
# affine건너뛰고 act_f통과시키는 작업으로 진행
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

print('x: {}\n{}\n'.format(x.shape, x.numpy()))
print('sigmoid(Tensorflow): {}\n{}'.format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print('tanh(Tensorflow): {}\n{}'.format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print('relu(Tensorflow): {}\n{}'.format(y_relu_tf.shape, y_relu_tf.numpy()))

x: (1, 5)
[[-0.8757808   0.3356369  -0.35219625 -0.30314562 -0.03882965]]

sigmoid(Tensorflow): (1, 5)
[[0.29405287 0.5831303  0.41284996 0.4247887  0.4902938 ]]
tanh(Tensorflow): (1, 5)
[[-0.70429933  0.32357663 -0.33832183 -0.29418862 -0.03881015]]
relu(Tensorflow): (1, 5)
[[0.        0.3356369 0.        0.        0.       ]]


In [23]:
# forward propagation(manual)
y_sigmoid_man = 1 / (1+tf.math.exp(-x))
y_tanh_man = (tf.math.exp(x) - tf.math.exp(-x)) / (tf.math.exp(x) + tf.math.exp(-x))
y_relu_man = tf.math.maximum(x,0)

print('x: {}\n{}\n'.format(x.shape, x.numpy()))
print('An with sigmoid(man): {}\n{}'.format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))
print('An with tanh(man): {}\n{}'.format(y_tanh_man.shape, y_tanh_man.numpy()))
print('An with relu(man): {}\n{}'.format(y_relu_man.shape, y_relu_man.numpy()))

x: (1, 5)
[[-0.8757808   0.3356369  -0.35219625 -0.30314562 -0.03882965]]

An with sigmoid(man): (1, 5)
[[0.29405284 0.5831303  0.41284993 0.42478868 0.49029383]]
An with tanh(man): (1, 5)
[[-0.70429933  0.32357663 -0.3383218  -0.29418865 -0.03881014]]
An with relu(man): (1, 5)
[[0.        0.3356369 0.        0.        0.       ]]


In [24]:
# Activation in Dense Layer
from tensorflow.keras.layers import Dense
tf.random.set_seed(10)
x = tf.random.normal(shape=(1,5))

# imp. Artificial neurons(AN)
dense_sigmoid = Dense(units=1, activation = 'sigmoid')
dense_tanh = Dense(units=1, activation = 'tanh')
dense_relu = Dense(units=1, activation = 'relu')

# forward propagation
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print('AN with sigmoid: {}\n{}'.format(y_sigmoid.shape, y_sigmoid.numpy()))
print('AN with tanh: {}\n{}'.format(y_tanh.shape, y_tanh.numpy()))
print('AN with relu: {}\n{}'.format(y_relu.shape, y_relu.numpy()))

AN with sigmoid: (1, 1)
[[0.498436]]
AN with tanh: (1, 1)
[[0.32123712]]
AN with relu: (1, 1)
[[0.]]


In [25]:
# forward propagation(manual)
W, b = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x,W) +b
a = 1 / (1 + tf.exp(-z))

print('Activation value(Tensorflow): {}\n{}'.format(y_sigmoid.shape, y_sigmoid.numpy()))
print('Activation value(Manual): {}\n{}'.format(a.shape, a.numpy()))

Activation value(Tensorflow): (1, 1)
[[0.498436]]
Activation value(Manual): (1, 1)
[[0.498436]]


In [26]:
# Minibatches, Shapes of Dense Layers
N, n_features = 8,10
tf.random.set_seed(10)
x = tf.random.normal(shape=(N, n_features))

dense = Dense(units=1, activation='relu')
y = dense(x)
W, b = dense.get_weights()

print('Shape of x: ', x.shape)
print('Shape of W: ', W.shape)
print('Shape of b: ', b.shape)

Shape of x:  (8, 10)
Shape of W:  (10, 1)
Shape of b:  (1,)


In [27]:
# Output Calculations
N, n_features = 8,10
tf.random.set_seed(10)
x = tf.random.normal(shape=(N, n_features))

dense = Dense(units=1, activation='sigmoid')
y_tf = dense(x)
W, b = dense.get_weights()

y_man = tf.linalg.matmul(x,W) + b
y_man = 1 / (1+tf.math.exp(-y_man))

print('Output(Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('Output(Manual): {}\n{}\n'.format(y_man.shape, y_man.numpy()))

Output(Tensorflow): (8, 1)
[[0.46854386]
 [0.5895974 ]
 [0.10466993]
 [0.8744323 ]
 [0.7818612 ]
 [0.47610277]
 [0.33888918]
 [0.7424137 ]]

Output(Manual): (8, 1)
[[0.46854383]
 [0.5895974 ]
 [0.10466997]
 [0.8744324 ]
 [0.7818612 ]
 [0.4761027 ]
 [0.33888915]
 [0.7424137 ]]

