# Activation Functions

In [9]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

In [4]:
tf.__version__

'2.5.0'

In [5]:
tf.random.set_seed(10)  # uniform 으로 쓰기도 하고 이거로 쓸때도 있음 - 중복없도록
x = tf.random.normal(shape=(1,5))

sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation(tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

print('x : {}\n{}'.format(x.shape, x.numpy()))
print('sigmoid(Tensorflow): {}\n{}'.format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print('tanh(Tensorflow): {}\n{}'.format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print('relu(Tensorflow): {}\n{}'.format(y_relu_tf.shape, y_relu_tf.numpy()))

x : (1, 5)
[[-0.8757808   0.3356369  -0.35219625 -0.30314562 -0.03882965]]
sigmoid(Tensorflow): (1, 5)
[[0.29405287 0.5831303  0.41284996 0.4247887  0.4902938 ]]
tanh(Tensorflow): (1, 5)
[[-0.70429933  0.32357663 -0.33832183 -0.29418862 -0.03881015]]
relu(Tensorflow): (1, 5)
[[0.        0.3356369 0.        0.        0.       ]]


In [10]:
# Activation in Dense Layer
from tensorflow.keras.layers import Dense
tf.random.set_seed(10)
x = tf.random.normal(shape=(1,5))

# imp. Artificial neurons
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print('An with sigmoid: {}\n{}'.format(y_sigmoid.shape, y_sigmoid.numpy()))
print('An with tanh: {}\n{}'.format(y_tanh.shape, y_tanh.numpy()))
print('An with relu: {}\n{}'.format(y_relu.shape, y_relu.numpy()))

An with sigmoid: (1, 1)
[[0.498436]]
An with tanh: (1, 1)
[[0.32123712]]
An with relu: (1, 1)
[[0.]]


In [ ]:
# forward propagation()
W, b = dense_sigmoid.get_weights()
z= tf.linalg.matmul(x,W) + b
a = 1 / (1+ tf.exp(-z))

print('sigmoid(manual): {}\n{}'.format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))
print('tanh(manual): {}\n{}'.format(y_tanh_man.shape, y_tanh_man.numpy()))
print('relue(manual): {}\n{}'.format(y_tanh_man.shape, y_tanh_man.numpy()))

In [7]:
# forward propagation(manual)
y_sigmoid_man = 1 / (1+tf.math.exp(-x))
y_tanh_man = (tf.math.exp() - tf.math.exp(-x)) / (tf.math.exp(x) + tf.math.exp(-x))
y_relu_man = tf.math.maxium(x, 0)

AttributeError: module 'tensorflow.math' has no attribute 'maxium'

In [13]:
# Minibatches, shapes of Dense Layers

N, n_features = 8, 10
tf.random.set_seed(10)
x = tf.random.normal(shape = (N, n_features))

dense = Dense(units=1, activation = 'relu')
y = dense(x)
W, b = dense.get_weights()

print('shape of x: ', x.shape)
print('shape of W:', W.shape)
print('Shape of b:',  b.shape)


shape of x:  (8, 10)
shape of W: (10, 1)
Shape of b: (1,)


In [16]:
## output calculations

N, n_features = 8, 10
tf.random.set_seed(10)
x = tf.random.normal(shape = (N, n_features))

dense = Dense(units=1, activation = 'sigmoid')
y_tf = dense(x)
W, b = dense.get_weights()


y_man = tf.linalg.matmul(x, W) + b
y_man = 1 / (1 + tf.math.exp(-y_man))

print('Output(tensorflow) : {}\n{}'.format(y_tf.shape, y_tf.numpy()))
print('Output(manual) : {}\n{}'.format(y_man.shape, y_man.numpy()))

Output(tensorflow) : (8, 1)
[[0.46854386]
 [0.5895974 ]
 [0.10466993]
 [0.8744323 ]
 [0.7818612 ]
 [0.47610277]
 [0.33888918]
 [0.7424137 ]]
Output(manual) : (8, 1)
[[0.46854386]
 [0.5895974 ]
 [0.10466997]
 [0.8744324 ]
 [0.7818612 ]
 [0.4761027 ]
 [0.33888912]
 [0.7424137 ]]
