## Affine Function

In [1]:
import tensorflow as tf 
from tensorflow.keras.layers import Dense

In [22]:
print(type(x))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [41]:
x = tf.constant([[10.]]) ## 불변은 콘스턴트, 변하는건 var
## Input setting(input -> matrix)


## dense 뉴련 생성
dense = Dense(units=1, activation = 'linear') ## unit : 뉴런 갯수, activation : 시그모이드, 탄, 등등

y_tf = dense(x) ## 뉴런에 인풋 넣기 ## a * 10 + b
## forward propagation + params initialization z = xw + b / 순방향 처리 

In [42]:
y_tf

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[13.19476]], dtype=float32)>

In [43]:
dense.get_weights()

[array([[1.319476]], dtype=float32), array([0.], dtype=float32)]

In [44]:
W, b = dense.get_weights()
print(W, b, y_tf.numpy())

[[1.319476]] [0.] [[13.19476]]


In [45]:
y_man = tf.linalg.matmul(x, W) + b ## matmul 은 행렬 계산을 시켜준다./ 
print(' ========== input / weight / bioase =============')
print('x : {}\n  {}\n'.format(x.shape, x.numpy()))
print('w: {}\n   {}\n'.format(W.shape, W))
print('b: {}\n   {}\n'.format(b.shape, b))

print('======= output ==========')
print('y(tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('y(manual) : {}\n{}\n'.format(y_man.shape, y_man.numpy()))

 ========== input / weight / bioase =============
x : (1, 1)
  [[10.]]

w: (1, 1)
   [[1.319476]]

b: (1,)
   [0.]

======= output ==========
y(tensorflow): (1, 1)
[[13.19476]]

y(manual) : (1, 1)
[[13.19476]]



In [51]:
# Params Intialzation

from tensorflow.keras.initializers import Constant

# weight / bias setting

W, b = (tf.constant(10.), tf.constant(20.))
w_init, b_init = Constant(W), Constant(b) ## 초기화 작업

dense = Dense(units = 1, activation = 'linear', kernel_initializer = w_init, bias_initializer = b_init)

y_tf = dense(x)
W, b = dense.get_weights()

print('W: {}\n{}\n'.format(W.shape, W))
print('b: {}\n{}\n'.format(b.shape, b))
print('affinefunction : ', W * x + b)
print('y_tf :', y_tf)

W: (1, 1)
[[10.]]

b: (1,)
[20.]

affinefunction :  tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
y_tf : tf.Tensor([[120.]], shape=(1, 1), dtype=float32)


## Affine Function with n Feature

In [52]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

## 랜덤을 고정시켜서 해보자. dense 
tf.random.set_seed(10) ## 사이킷런 하는 것 처럼 아무 값이나 넣으면 된다. 
x = tf.random.uniform(shape = (1,10), minval = 0, maxval = 10)
print(x.numpy())
dense = Dense(units = 1)
print(dense)



[[6.4415097  8.082472   8.976547   6.3689017  6.270969   9.936013
  0.23594856 0.36683917 5.8605776  5.7403145 ]]


In [54]:
y_tf = dense(x)
W, b = dense.get_weights()
y_man = tf.linalg.matmul(x, W) + b ## 행렬 곱 시키는 것 matmul


In [56]:
print(' ========== input / weight / bioase =============')
print('x : {}\n  {}\n'.format(x.shape, x.numpy()))
print('w: {}\n   {}\n'.format(W.shape, W))
print('b: {}\n   {}\n'.format(b.shape, b))

print('======= output ==========')
print('y(tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('y(manual) : {}\n{}\n'.format(y_man.shape, y_man.numpy()))

 ========== input / weight / bioase =============
x : (1, 10)
  [[6.4415097  8.082472   8.976547   6.3689017  6.270969   9.936013
  0.23594856 0.36683917 5.8605776  5.7403145 ]]

w: (10, 1)
   [[ 0.08091772]
 [-0.10844558]
 [-0.5296768 ]
 [ 0.30087596]
 [-0.18808389]
 [ 0.29202002]
 [-0.39361012]
 [ 0.09546101]
 [-0.4453573 ]
 [ 0.6689041 ]]

b: (1,)
   [0.]

======= output ==========
y(tensorflow): (1, 1)
[[-0.29983282]]

y(manual) : (1, 1)
[[-0.29983282]]

