## 멀티 퍼셉트론 순뱡향 패스

In [1]:
import numpy as np 
import pandas as pd 

### 활성화 함수 : 시그모이드

In [4]:
def actf(x):
    return 1 / (1+np.exp(-x))

### 시그모이드 함수의 미분치(역함수)

In [5]:
def actf_deriv(x):
    return x * (1 - x) 

### Odds
- odds는 프로바빌리티의 또 다른 표현법
- 어던 사건이 일어날 확률을 p라고 한다면, odds는 p(1-p)로 구현된다
- odds는 질병 발병 확률 또는 도박 배팅의 확률을 표현할 때 많있슴

- odds = p /1 - p 

- logit 은 odds에 로그를 씌운것



### 입력 유닛 개수, 은닉 유닛 개수, 출력 유닛 개수

In [6]:
inputs, hidden, outputs = 2,2,1
learning_rate = 0.2 

In [8]:
## 학습 샘플과 정답 xor
X = np.array([[0,0],[0,1],[1,0],[1,1]])
T = np.array([[0],[1],[1],[0]])

In [9]:
## 훈련데이터
W1 = np.array([[0.10,0.20], [0.30,0.40]])
W2 = np.array([[0.50], [0.60]])
B1 = np.array([0.1,0.2])
B2 = np.array([0.3])

In [10]:
## 순방향 전파 계산
def predict(X):
    layer0 = X ## 입력을 layer0에 대입
    Z1 = np.dot(layer0, W1) + B1 ## 입력값에 대해 aiffine function 계산: 행렬 곱
    layer1 = actf(Z1) ## ## 활성화 함수 (시그모이드)
    Z2 = np.dot(layer1, W2) + B2 ## layer1에 대해 aiffine function 계산
    layer2 = actf(Z2) ## 활성화 함수 (시그모이드)
    return layer0, layer1, layer2


In [14]:
def test():
    for x, y in zip(X, T):
        x = np.reshape(x, (1,-1))
        layer0, layer1, layer2 = predict(x)
        print(x, y, layer2)

In [15]:
test()

[[0 0]] [0] [[0.70938314]]
[[0 1]] [1] [[0.72844306]]
[[1 0]] [1] [[0.71791234]]
[[1 1]] [0] [[0.73598705]]
